# Generated by Django 4.1.7 on 2023-02-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindfulCoach', '0002_appointment_rename_user_userex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='UserEx',
        ),
    ]
